### ISSUE TITLE
Transform my own data

### ISSUE THREAD

**Issue by JoeHEZHAO** [Cadene/tensorflow-model-zoo.torch#4]
Hi 

Thanks for your great work.

Is it possible to transform my own pre-trained model in tensorflow to pytorch ? May I ask which tool are you using for transform ?

Best
Joe

**Comment by Cadene** [comment]
Yes it is possible, but a bit fastidious if your network is big, because you should do it by hand most probably. 

You should look at those two files :)

https://github.com/Cadene/tensorflow-model-zoo.torch/blob/master/nasnet/tensorflow_dump.py

https://github.com/Cadene/tensorflow-model-zoo.torch/blob/master/nasnet/pytorch_load.py
